services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - storage:/app/storage
      - db:/app/data
    restart: unless-stopped

volumes:
  storage:
  db:
